In [1]:
import numpy as np
import pandas as pd

In [4]:
frame = pd.DataFrame(np.arange(8).reshape((2,4)), index=['three', 'one'], columns=['d', 'a', 'b', 'c'])
frame = frame.sort_index()

In [5]:
frame

d  a  b  c
one    4  5  6  7
three  0  1  2  3

In [6]:
arr = np.arange(12.).reshape((3, 4))

In [7]:
print(arr - arr[0])

[[0. 0. 0. 0.]
 [4. 4. 4. 4.]
 [8. 8. 8. 8.]]


In [10]:
frame=pd.DataFrame({'a':[0,1,0,1],'b':[4,7,-3,2]})

In [11]:
frane=frame.sort_values(by=['a','b'])

In [13]:
frane

a  b
2  0 -3
0  0  4
3  1  2
1  1  7

In [14]:
a=[1,2,3]
b=[4,5,6]

In [20]:
b.append(a)