In [1]:
import pandas as pd

In [2]:
df = pd.DataFrame(
{
    'name': ['Ali', 'Zahid', 'Ubaid'],
    'age': [18, 20, 18]
}
)

In [3]:
df

name  age
0    Ali   18
1  Zahid   20
2  Ubaid   18

In [4]:
df['age']=df['age'].replace({18:25})

In [5]:
df

name  age
0    Ali   25
1  Zahid   20
2  Ubaid   25

In [6]:
df.iloc[0,1]=37

In [7]:
df

name  age
0    Ali   37
1  Zahid   20
2  Ubaid   25

In [8]:
df['name'].replace(['Ali', 'Zahid'],['No name', ' '])

0    No name
1           
2      Ubaid
Name: name, dtype: object

In [9]:
df['name'].replace({'Ali': 'No name', 'Zahid': ' '})

0    No name
1           
2      Ubaid
Name: name, dtype: object

In [10]:
df['name'].replace(['Ali','Zahid'],'No name')

0    No name
1    No name
2      Ubaid
Name: name, dtype: object

In [11]:
df

name  age
0    Ali   37
1  Zahid   20
2  Ubaid   25

In [12]:
# Map

In [13]:
df['age'].map(lambda age: 'Older' if age>25 else 'Younger')

0      Older
1    Younger
2    Younger
Name: age, dtype: object

In [14]:
 # Assignment : what is the different between map and apply

In [15]:
#map with index we can also apply map to index map can be used to convert a specific column or index to a new value

In [16]:
import numpy as np

In [17]:
df = pd.DataFrame(
    np.arange(0, 12).reshape(3, 4),
    index=['A', 'B', 'C'],
    columns = ['C1', 'C2', 'C3', 'C4']
)

In [18]:
df

C1  C2  C3  C4
A   0   1   2   3
B   4   5   6   7
C   8   9  10  11

In [19]:
display(df)
print(df.loc['A'])
print(df.iloc[1])

C1  C2  C3  C4
A   0   1   2   3
B   4   5   6   7
C   8   9  10  11

C1    0
C2    1
C3    2
C4    3
Name: A, dtype: int32
C1    4
C2    5
C3    6
C4    7
Name: B, dtype: int32


In [20]:
df.index

Index(['A', 'B', 'C'], dtype='object')

In [21]:
index_to_country = {
    'A': 'Australia',
    'B': 'Brazil',
    'C': 'China'
}

In [22]:
df.index = df.index.map(index_to_country)

In [23]:
df

C1  C2  C3  C4
Australia   0   1   2   3
Brazil      4   5   6   7
China       8   9  10  11

In [24]:
df.loc['Australia']

C1    0
C2    1
C3    2
C4    3
Name: Australia, dtype: int32

In [25]:
# other index method

In [26]:
df.rename(index=str.upper, columns=str.lower) # changing column / index to upper/ lower case

c1  c2  c3  c4
AUSTRALIA   0   1   2   3
BRAZIL      4   5   6   7
CHINA       8   9  10  11

In [27]:
df.rename(index={'China': 'coulambia'},
         columns={'C1': 'C11'})

C11  C2  C3  C4
Australia    0   1   2   3
Brazil       4   5   6   7
coulambia    8   9  10  11

In [28]:
df.rename(index={'China': 'coulambia'},inplace=True)

In [29]:
df

C1  C2  C3  C4
Australia   0   1   2   3
Brazil      4   5   6   7
coulambia   8   9  10  11

In [30]:
# Discretization and binning: to place items into respective buckets / bins if they lie in a specific rage

In [31]:
"""
88+ -> A
75-87 -> B
60-74 -> C
<60 -> F

"""

'\n88+ -> A\n75-87 -> B\n60-74 -> C\n<60 -> F\n\n'

In [32]:
marks = [90, 22, 25, 67, 81, 83, 87]
bins = [0, 60, 75, 88, 100]
cats = pd.cut(marks, bins)

In [33]:
cats.codes

array([3, 0, 0, 1, 2, 2, 2], dtype=int8)

In [34]:
cats.categories

IntervalIndex([(0, 60], (60, 75], (75, 88], (88, 100]], dtype='interval[int64, right]')

In [35]:
# (,) - close intervel, exclusive
# [,] - open intervel, inclusive

In [36]:
pd.value_counts(cats)

(75, 88]     3
(0, 60]      2
(60, 75]     1
(88, 100]    1
dtype: int64

In [37]:
cats = pd.cut(marks, bins, labels=['F', 'c', 'B', 'A'])

In [38]:
cats.codes

array([3, 0, 0, 1, 2, 2, 2], dtype=int8)

In [39]:
cats.categories

Index(['F', 'c', 'B', 'A'], dtype='object')

In [40]:
 pd.value_counts(cats)

B    3
F    2
c    1
A    1
dtype: int64

In [41]:
print(cats.categories)
print(cats.codes)

Index(['F', 'c', 'B', 'A'], dtype='object')
[3 0 0 1 2 2 2]


In [42]:
marks

[90, 22, 25, 67, 81, 83, 87]

In [43]:
df.describe()

C1   C2    C3    C4
count  3.0  3.0   3.0   3.0
mean   4.0  5.0   6.0   7.0
std    4.0  4.0   4.0   4.0
min    0.0  1.0   2.0   3.0
25%    2.0  3.0   4.0   5.0
50%    4.0  5.0   6.0   7.0
75%    6.0  7.0   8.0   9.0
max    8.0  9.0  10.0  11.0

In [44]:
 df[np.abs(df['C2'])>5]

C1  C2  C3  C4
coulambia   8   9  10  11

In [45]:
# Capping data outside the range
# capping putting the value on the edge values
df[np.abs(df['C2']) > 5] = np.sign(df) * 5  # -7 => -5, 8 => 5

In [46]:
df

C1  C2  C3  C4
Australia   0   1   2   3
Brazil      4   5   6   7
coulambia   5   5   5   5

In [47]:
# merging two data frames : it is similar to SQL joins two data frame based on common column

In [48]:
df1 = pd.DataFrame(
    {
        'Id': [1, 2, 3],
        'Name': ['John', 'Peter', 'Silbert']
    }
)

In [49]:
df2 = pd.DataFrame(
    {
        'Id': [1, 2, 3],
        'Salary': ['1150', '170', '190']
    }
)

In [50]:
display(df1)
display(df2)

Id     Name
0   1     John
1   2    Peter
2   3  Silbert

Id Salary
0   1   1150
1   2    170
2   3    190

In [51]:
pd.merge(df1,df2)

Id     Name Salary
0   1     John   1150
1   2    Peter    170
2   3  Silbert    190

In [52]:
# when the common column name doesn't match

In [53]:
df2 = pd.DataFrame(
    {
        'Emp_Id': [1, 2, 3],
        'Salary': ['1150', '170', '190']
    }
)

In [54]:
pd.merge(df1, df2, left_on='Id', right_on='Emp_Id')

Id     Name  Emp_Id Salary
0   1     John       1   1150
1   2    Peter       2    170
2   3  Silbert       3    190

In [55]:
df1 = pd.DataFrame({'Id': [1, 2, 3],
        'Name': ['John', 'Peter', 'Silbert']})

In [57]:
df2 = pd.DataFrame(
    {
        'Id': [1, 2, 3],
        'Salary': ['1150', '170', '190', 90]
    }
)

ValueError: All arrays must be of the same length

In [58]:
pd.merge(df1, df2, how='right')

MergeError: No common columns to perform merge on. Merge options: left_on=None, right_on=None, left_index=False, right_index=False

In [59]:
# Concatenating two dataframes

In [60]:
df1

Id     Name
0   1     John
1   2    Peter
2   3  Silbert

In [61]:
df2 = pd.DataFrame(
    {
        'Id': [4, 5],
        'Name': ['Ryo', 'Pawan']
    }
)

In [62]:
pd.concat([df1, df2]) # Row wise concatenation

Id     Name
0   1     John
1   2    Peter
2   3  Silbert
0   4      Ryo
1   5    Pawan

In [63]:
pd.concat([df1, df2], axis=1) # Column wise concatenation

Id     Name   Id   Name
0   1     John  4.0    Ryo
1   2    Peter  5.0  Pawan
2   3  Silbert  NaN    NaN

In [64]:
df1 = pd.DataFrame(
    {
        'Id': [1, 2, 3],
        'Name': ['John', 'Peter', 'Silbert'],
        'Ages': [np.nan, '40', np.nan]
    }
)

In [65]:
df2 = pd.DataFrame(
    {
        'Id': [1, 2, 3],
        'Ages': ['23', np.nan, '40']
    }
)

In [66]:
display(df1)
display(df2)

Id     Name Ages
0   1     John  NaN
1   2    Peter   40
2   3  Silbert  NaN

Id Ages
0   1   23
1   2  NaN
2   3   40

In [67]:
df1.combine_first(df2)

Ages  Id     Name
0   23   1     John
1   40   2    Peter
2   40   3  Silbert