# NumPy

***Slicing***

In [1]:
import numpy as np

In [6]:
a = np.arange(27).reshape(3,3,3)
print(a.shape)
print(a.ndim)
a

(3, 3, 3)
3


array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [3]:
a = np.arange(100).reshape(10,10)

In [4]:
a

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [8]:
# 4 pictures resolution 8*8
pic = np.arange(4*8*8).reshape(4,8,8)

In [9]:
pic

array([[[  0,   1,   2,   3,   4,   5,   6,   7],
        [  8,   9,  10,  11,  12,  13,  14,  15],
        [ 16,  17,  18,  19,  20,  21,  22,  23],
        [ 24,  25,  26,  27,  28,  29,  30,  31],
        [ 32,  33,  34,  35,  36,  37,  38,  39],
        [ 40,  41,  42,  43,  44,  45,  46,  47],
        [ 48,  49,  50,  51,  52,  53,  54,  55],
        [ 56,  57,  58,  59,  60,  61,  62,  63]],

       [[ 64,  65,  66,  67,  68,  69,  70,  71],
        [ 72,  73,  74,  75,  76,  77,  78,  79],
        [ 80,  81,  82,  83,  84,  85,  86,  87],
        [ 88,  89,  90,  91,  92,  93,  94,  95],
        [ 96,  97,  98,  99, 100, 101, 102, 103],
        [104, 105, 106, 107, 108, 109, 110, 111],
        [112, 113, 114, 115, 116, 117, 118, 119],
        [120, 121, 122, 123, 124, 125, 126, 127]],

       [[128, 129, 130, 131, 132, 133, 134, 135],
        [136, 137, 138, 139, 140, 141, 142, 143],
        [144, 145, 146, 147, 148, 149, 150, 151],
        [152, 153, 154, 155, 156, 157, 158, 15

In [10]:
# 10 pictures resolution 8*8
pic = np.arange(10*8*8).reshape(10,8,8)
pic

array([[[  0,   1,   2,   3,   4,   5,   6,   7],
        [  8,   9,  10,  11,  12,  13,  14,  15],
        [ 16,  17,  18,  19,  20,  21,  22,  23],
        [ 24,  25,  26,  27,  28,  29,  30,  31],
        [ 32,  33,  34,  35,  36,  37,  38,  39],
        [ 40,  41,  42,  43,  44,  45,  46,  47],
        [ 48,  49,  50,  51,  52,  53,  54,  55],
        [ 56,  57,  58,  59,  60,  61,  62,  63]],

       [[ 64,  65,  66,  67,  68,  69,  70,  71],
        [ 72,  73,  74,  75,  76,  77,  78,  79],
        [ 80,  81,  82,  83,  84,  85,  86,  87],
        [ 88,  89,  90,  91,  92,  93,  94,  95],
        [ 96,  97,  98,  99, 100, 101, 102, 103],
        [104, 105, 106, 107, 108, 109, 110, 111],
        [112, 113, 114, 115, 116, 117, 118, 119],
        [120, 121, 122, 123, 124, 125, 126, 127]],

       [[128, 129, 130, 131, 132, 133, 134, 135],
        [136, 137, 138, 139, 140, 141, 142, 143],
        [144, 145, 146, 147, 148, 149, 150, 151],
        [152, 153, 154, 155, 156, 157, 158, 15

In [11]:
np.random.randint(0,255,(10,8,8))

array([[[ 84, 102,  19, 158,  18,  35, 218,  27],
        [ 36, 132,  58, 223, 245, 153,  13, 104],
        [105,  48,  94,  16,  34, 207, 188,  43],
        [ 95, 209, 124,  97,   7, 240, 138, 184],
        [ 68,  11,  21,  16,  57,  33,  37, 172],
        [112,  77, 185, 109,  40, 224, 236, 215],
        [195, 237,  87,  72, 245,  26, 144,  70],
        [  8,  64,  93, 175, 119,  74,  96, 124]],

       [[228,  10,   7,  35, 231, 107,  55, 247],
        [171, 104, 222,  42, 181, 230, 208,  81],
        [ 93, 218, 247,  19, 175, 118, 189, 241],
        [189, 223, 219, 120, 116,  15, 242, 127],
        [  7,  71,  66,  89,  25,  32, 124,  41],
        [ 43, 248,  14, 122,  88, 105,  58,  97],
        [  9, 236,  36, 161,  67,  70,  45,  98],
        [106, 219, 239, 171, 174,  55, 192, 188]],

       [[  4, 145,  97,  71, 195, 247, 223, 121],
        [ 93, 158, 172,  28, 117,  18, 188,  83],
        [ 39, 141, 116, 107,   5, 100, 101, 170],
        [ 91, 201,  74,  96,  17,  22, 190,  5

Create NumPy array

In [16]:
a = np.array([1,2,3])
print(a)
display(a)

[1 2 3]


array([1, 2, 3])

In [17]:
display(a)

array([1, 2, 3])

In [19]:
a = np.array([[1,2,3],
             [4,5,6]])
display(a)
print(a.shape)
a[]

array([[1, 2, 3],
       [4, 5, 6]])

# How to create a basic array

In [20]:
display(np.zeros(10))

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [22]:
display(np.ones(10))

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [24]:
display(np.empty(10))

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [28]:
# Function
np.linspace(1,2,7)

array([1.        , 1.16666667, 1.33333333, 1.5       , 1.66666667,
       1.83333333, 2.        ])

In [30]:
np.linspace(1,60,3)

array([ 1. , 30.5, 60. ])

In [32]:
a = np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [33]:
# Fuction
np.ones_like(a)

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

In [34]:
np.empty_like(a)

array([  0,   1,   0, 556, 952,   0, 768,   0,   0,   0])

***Sorting***

In [36]:
a = np.array([1,3,6,3,6,7,8,4,3,5,7])
np.sort(a)

array([1, 3, 3, 3, 4, 5, 6, 6, 7, 7, 8])

**(-1 is used to insert unknown or autofill value)**

In [37]:
a = np.arange(2*2).reshape(2,-1)
a

array([[0, 1],
       [2, 3]])

In [38]:
a = np.arange(2*2).reshape(-1,2)
a

array([[0, 1],
       [2, 3]])

# arg
 - "arg" function give index of value

In [44]:
#             0 1 2 3 4 5 6
a = np.array([1,7,4,9,4,7,4])
np.argmax(a)

3

In [45]:
np.argmin(a)

0

In [46]:
np.argsort(a)

array([0, 2, 4, 6, 1, 5, 3], dtype=int64)

In [50]:
labels = ['cat', 'dog', 'apple', 'Orange']
prediction = [70,5,10,15]
index = np.argmax(prediction) # max index probability
print(labels[index])

cat


# Concatinaton
 - 

In [51]:
a = np.arange(1,11).reshape(5,2)
b = np.arange(11,21).reshape(5,2)
display(a)
display(b)

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10]])

array([[11, 12],
       [13, 14],
       [15, 16],
       [17, 18],
       [19, 20]])

In [55]:
np.concatenate((a,b))

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10],
       [11, 12],
       [13, 14],
       [15, 16],
       [17, 18],
       [19, 20]])

In [56]:
np.concatenate((a,b), axis=1)

array([[ 1,  2, 11, 12],
       [ 3,  4, 13, 14],
       [ 5,  6, 15, 16],
       [ 7,  8, 17, 18],
       [ 9, 10, 19, 20]])

In [57]:
np.concatenate((a,b), axis=0)

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10],
       [11, 12],
       [13, 14],
       [15, 16],
       [17, 18],
       [19, 20]])

In [59]:
# Making stake
np.stack((a,b))

array([[[ 1,  2],
        [ 3,  4],
        [ 5,  6],
        [ 7,  8],
        [ 9, 10]],

       [[11, 12],
        [13, 14],
        [15, 16],
        [17, 18],
        [19, 20]]])

In [60]:
np.stack((a,b), axis=1)

array([[[ 1,  2],
        [11, 12]],

       [[ 3,  4],
        [13, 14]],

       [[ 5,  6],
        [15, 16]],

       [[ 7,  8],
        [17, 18]],

       [[ 9, 10],
        [19, 20]]])

In [62]:
a = np.arange(2*2*2).reshape(2,2,2)
a.sum()

28

In [64]:
display(a)
a.sum(axis=0)

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

array([[ 4,  6],
       [ 8, 10]])

In [66]:
display(a)
a.sum(axis=1)

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

array([[ 2,  4],
       [10, 12]])

In [67]:
display(a)
a.sum(axis=2)

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

array([[ 1,  5],
       [ 9, 13]])

# Indexing, Slicing, Fancy Slicing, Boolean Slicing

In [68]:
a = np.arange(2*4*4).reshape(-1,4,4)
a

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11],
        [12, 13, 14, 15]],

       [[16, 17, 18, 19],
        [20, 21, 22, 23],
        [24, 25, 26, 27],
        [28, 29, 30, 31]]])

In [72]:
print(a[0])

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]


In [73]:
display(a)
a % 2 == 0

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11],
        [12, 13, 14, 15]],

       [[16, 17, 18, 19],
        [20, 21, 22, 23],
        [24, 25, 26, 27],
        [28, 29, 30, 31]]])

array([[[ True, False,  True, False],
        [ True, False,  True, False],
        [ True, False,  True, False],
        [ True, False,  True, False]],

       [[ True, False,  True, False],
        [ True, False,  True, False],
        [ True, False,  True, False],
        [ True, False,  True, False]]])

In [76]:
b = np.arange(1,7)
display(b)
b%2==0

array([1, 2, 3, 4, 5, 6])

array([False,  True, False,  True, False,  True])

In [77]:
display(a)
a[a%2==0] & 

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11],
        [12, 13, 14, 15]],

       [[16, 17, 18, 19],
        [20, 21, 22, 23],
        [24, 25, 26, 27],
        [28, 29, 30, 31]]])

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30])

In [ ]:
# deep copy
# shallow copy: one umair two names such as umair and khankhaila