# Numpy
 - Numerical Python
 - Fastest
 - Vectorized Operation 
 - Contigous Memory

In [3]:
# Creation a numpy array
# !pip install numpy
import numpy as np


In [4]:
# creating an arry using a python list
x = np.array([22,33,44,55])
x

array([22, 33, 44, 55])

In [5]:
x.size

4

In [6]:
# 1 dimention array = Vector
# 2 dimention array = Matrix
# 3 dimention array = Cube
# n dimention array = .....
x.shape

(4,)

In [7]:
x.ndim

1

In [8]:
list(range(10))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [10]:
arr1d = np.arange(10)
arr1d

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [12]:
arr2d =  np.array([[1,2,3],[11,22,33],[111,222,333],[1111,2222,3333]])

In [13]:
arr2d

array([[   1,    2,    3],
       [  11,   22,   33],
       [ 111,  222,  333],
       [1111, 2222, 3333]])

In [18]:
arr2d.shape

(4, 3)

In [45]:
# arr2d = np.arange(20).reshape(1,20)
# arr2d = np.arange(20).reshape(20,1)
arr2d = np.arange(20).reshape(5,4)
# arr2d = np.arange(20).reshapesh(4,5)
# arr2d = np.arange(20).reshapesh(10,2)
# arr2d = np.arange(20).reshapesh(2,10)
arr2d

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [23]:
arr2d.shape

(1, 20)

In [24]:
arr2d.ndim

2

In [25]:
arr2d.reshape(20)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [26]:
arr2d.flatten()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [27]:
arr2d.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [35]:
# note if we add SB[], the number of dimension will increase

arr = np.array([[[10]]])
arr

array([[[10]]])

In [37]:
# this is a scalar quantity there is no dimesion in scalar
arr = np.array(10)

In [38]:
arr.ndim

0

In [40]:
# 1d vector
arr = np.array([10])
arr

array([10])

In [41]:
# 2d vector
arr = np.array([[10]])
arr

array([[10]])

In [48]:
arr3d = np.arange(64).reshape(4,4,4)# (depth, row, colums)
                                    # (matrix, row, col)
arr3d

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11],
        [12, 13, 14, 15]],

       [[16, 17, 18, 19],
        [20, 21, 22, 23],
        [24, 25, 26, 27],
        [28, 29, 30, 31]],

       [[32, 33, 34, 35],
        [36, 37, 38, 39],
        [40, 41, 42, 43],
        [44, 45, 46, 47]],

       [[48, 49, 50, 51],
        [52, 53, 54, 55],
        [56, 57, 58, 59],
        [60, 61, 62, 63]]])

In [50]:
arr2d.reshape(2,10)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19]])

In [53]:
arr2d = np.arange(20).reshape(2,10)
arr2d

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19]])

In [56]:
arr2d[0,5]
#  or
arr2d[0][5]

5

In [57]:
arr2d[1,6]
#  or
arr2d[1][6]

16

In [58]:
arr3d[0]

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [59]:
arr3d

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11],
        [12, 13, 14, 15]],

       [[16, 17, 18, 19],
        [20, 21, 22, 23],
        [24, 25, 26, 27],
        [28, 29, 30, 31]],

       [[32, 33, 34, 35],
        [36, 37, 38, 39],
        [40, 41, 42, 43],
        [44, 45, 46, 47]],

       [[48, 49, 50, 51],
        [52, 53, 54, 55],
        [56, 57, 58, 59],
        [60, 61, 62, 63]]])

In [60]:
  arr3d[3,2,2]

58

In [61]:
x

array([22, 33, 44, 55])

In [62]:
z = []
for i in x:
    z.append(i*2)
z

[44, 66, 88, 110]

In [64]:
[i**2for i in x]

[484, 1089, 1936, 3025]

In [65]:
x*2

array([ 44,  66,  88, 110])

In [66]:
arr2d / 10

array([[0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9],
       [1. , 1.1, 1.2, 1.3, 1.4, 1.5, 1.6, 1.7, 1.8, 1.9]])

In [67]:
arr3d

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11],
        [12, 13, 14, 15]],

       [[16, 17, 18, 19],
        [20, 21, 22, 23],
        [24, 25, 26, 27],
        [28, 29, 30, 31]],

       [[32, 33, 34, 35],
        [36, 37, 38, 39],
        [40, 41, 42, 43],
        [44, 45, 46, 47]],

       [[48, 49, 50, 51],
        [52, 53, 54, 55],
        [56, 57, 58, 59],
        [60, 61, 62, 63]]])

In [68]:
a = arr3d[2,1,2] * 10
a

380

In [69]:
arr3d

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11],
        [12, 13, 14, 15]],

       [[16, 17, 18, 19],
        [20, 21, 22, 23],
        [24, 25, 26, 27],
        [28, 29, 30, 31]],

       [[32, 33, 34, 35],
        [36, 37, 38, 39],
        [40, 41, 42, 43],
        [44, 45, 46, 47]],

       [[48, 49, 50, 51],
        [52, 53, 54, 55],
        [56, 57, 58, 59],
        [60, 61, 62, 63]]])

In [70]:
arr3d[2,1,2] = arr3d[2,1,2]*10

In [71]:
arr3d[2,1,2]

380

In [72]:
x

array([22, 33, 44, 55])

In [73]:
y = np.arange(4)

In [74]:
y

array([0, 1, 2, 3])

In [75]:
x+y

array([22, 34, 46, 58])

In [77]:
a = np.arange(25).reshape(5,5)
b = np.arange(25,50).reshape(5,5)

In [78]:
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [79]:
b

array([[25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34],
       [35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44],
       [45, 46, 47, 48, 49]])

In [80]:
# mirror or element wise
a + b

array([[25, 27, 29, 31, 33],
       [35, 37, 39, 41, 43],
       [45, 47, 49, 51, 53],
       [55, 57, 59, 61, 63],
       [65, 67, 69, 71, 73]])

In [81]:
a * b

array([[   0,   26,   54,   84,  116],
       [ 150,  186,  224,  264,  306],
       [ 350,  396,  444,  494,  546],
       [ 600,  656,  714,  774,  836],
       [ 900,  966, 1034, 1104, 1176]])

In [84]:
# a@b
# or
a.dot(b)

array([[ 400,  410,  420,  430,  440],
       [1275, 1310, 1345, 1380, 1415],
       [2150, 2210, 2270, 2330, 2390],
       [3025, 3110, 3195, 3280, 3365],
       [3900, 4010, 4120, 4230, 4340]])

In [85]:
c = np.arange(20).reshape(5,4)

In [86]:
c

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [87]:
# b(5,5) and c(5,4)
# col of 1st matrix and rows of 2nd matrix will be equal 
b@c

array([[1120, 1255, 1390, 1525],
       [1320, 1480, 1640, 1800],
       [1520, 1705, 1890, 2075],
       [1720, 1930, 2140, 2350],
       [1920, 2155, 2390, 2625]])

In [88]:
c@b # not woring because its rows and column does not match

ValueError: matmul: Input operand 1 has a mismatch in its core dimension 0, with gufunc signature (n?,k),(k,m?)->(n?,m?) (size 5 is different from 4)

# Array slicing

In [89]:
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [90]:
a[2,3]

13

In [91]:
type(a[2,3])

numpy.int32

In [92]:
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [93]:
# array [row, col]
#       [start:end, start:end]

In [94]:
a[2:3, 3:4]

array([[13]])

# Quarrying Array

In [95]:
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [97]:
mask = a>5 # Mask
mask

array([[False, False, False, False, False],
       [False,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True]])

In [98]:
a[mask]

array([ 6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22,
       23, 24])

In [99]:
a[a>10]

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24])

In [100]:
a[a>7] = 100

In [101]:
a

array([[  0,   1,   2,   3,   4],
       [  5,   6,   7, 100, 100],
       [100, 100, 100, 100, 100],
       [100, 100, 100, 100, 100],
       [100, 100, 100, 100, 100]])

In [102]:
np.where(a>10, 0, a)

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

In [103]:
# mask is nothing but a query which is store in a variable like this
a[(a%2==0) & (a%7==0)]

array([0])

In [104]:
a[(a%2==0) | (a%7==0)]

array([  0,   2,   4,   6,   7, 100, 100, 100, 100, 100, 100, 100, 100,
       100, 100, 100, 100, 100, 100, 100, 100, 100])

In [105]:
# in this case when condition are true then replace "wow" and false "Oh"
np.where((a%2==0) | (a%7==0), "Wow", "Oh")

array([['Wow', 'Oh', 'Wow', 'Oh', 'Wow'],
       ['Oh', 'Wow', 'Wow', 'Wow', 'Wow'],
       ['Wow', 'Wow', 'Wow', 'Wow', 'Wow'],
       ['Wow', 'Wow', 'Wow', 'Wow', 'Wow'],
       ['Wow', 'Wow', 'Wow', 'Wow', 'Wow']], dtype='<U3')

# Combining  Arrays

In [107]:
print(a)
a.shape

[[  0   1   2   3   4]
 [  5   6   7 100 100]
 [100 100 100 100 100]
 [100 100 100 100 100]
 [100 100 100 100 100]]


(5, 5)

In [108]:
print(b)
b.shape

[[25 26 27 28 29]
 [30 31 32 33 34]
 [35 36 37 38 39]
 [40 41 42 43 44]
 [45 46 47 48 49]]


(5, 5)

In [115]:
# in numpy array for concatination use "1" for column and "0" for row
print(np.concatenate((a,b), axis=1))
print("\n\nthis is space\n\n")
print(np.concatenate((a,b), axis=0))

[[  0   1   2   3   4  25  26  27  28  29]
 [  5   6   7 100 100  30  31  32  33  34]
 [100 100 100 100 100  35  36  37  38  39]
 [100 100 100 100 100  40  41  42  43  44]
 [100 100 100 100 100  45  46  47  48  49]]


this is space


[[  0   1   2   3   4]
 [  5   6   7 100 100]
 [100 100 100 100 100]
 [100 100 100 100 100]
 [100 100 100 100 100]
 [ 25  26  27  28  29]
 [ 30  31  32  33  34]
 [ 35  36  37  38  39]
 [ 40  41  42  43  44]
 [ 45  46  47  48  49]]


In [116]:
np.stack((a,b))

array([[[  0,   1,   2,   3,   4],
        [  5,   6,   7, 100, 100],
        [100, 100, 100, 100, 100],
        [100, 100, 100, 100, 100],
        [100, 100, 100, 100, 100]],

       [[ 25,  26,  27,  28,  29],
        [ 30,  31,  32,  33,  34],
        [ 35,  36,  37,  38,  39],
        [ 40,  41,  42,  43,  44],
        [ 45,  46,  47,  48,  49]]])

In [117]:
np.hstack((a,b))

array([[  0,   1,   2,   3,   4,  25,  26,  27,  28,  29],
       [  5,   6,   7, 100, 100,  30,  31,  32,  33,  34],
       [100, 100, 100, 100, 100,  35,  36,  37,  38,  39],
       [100, 100, 100, 100, 100,  40,  41,  42,  43,  44],
       [100, 100, 100, 100, 100,  45,  46,  47,  48,  49]])

In [118]:
np.vstack((a,b))

array([[  0,   1,   2,   3,   4],
       [  5,   6,   7, 100, 100],
       [100, 100, 100, 100, 100],
       [100, 100, 100, 100, 100],
       [100, 100, 100, 100, 100],
       [ 25,  26,  27,  28,  29],
       [ 30,  31,  32,  33,  34],
       [ 35,  36,  37,  38,  39],
       [ 40,  41,  42,  43,  44],
       [ 45,  46,  47,  48,  49]])

In [119]:
np.column_stack((a,b))

array([[  0,   1,   2,   3,   4,  25,  26,  27,  28,  29],
       [  5,   6,   7, 100, 100,  30,  31,  32,  33,  34],
       [100, 100, 100, 100, 100,  35,  36,  37,  38,  39],
       [100, 100, 100, 100, 100,  40,  41,  42,  43,  44],
       [100, 100, 100, 100, 100,  45,  46,  47,  48,  49]])

In [120]:
np.row_stack((a,b))

array([[  0,   1,   2,   3,   4],
       [  5,   6,   7, 100, 100],
       [100, 100, 100, 100, 100],
       [100, 100, 100, 100, 100],
       [100, 100, 100, 100, 100],
       [ 25,  26,  27,  28,  29],
       [ 30,  31,  32,  33,  34],
       [ 35,  36,  37,  38,  39],
       [ 40,  41,  42,  43,  44],
       [ 45,  46,  47,  48,  49]])

# Split Function

In [132]:
# np.split(a,2, axis = 0)
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [128]:
a = np.arange(16).reshape(4,4)
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [129]:
np.split(a,2, axis=1)

[array([[ 0,  1],
        [ 4,  5],
        [ 8,  9],
        [12, 13]]),
 array([[ 2,  3],
        [ 6,  7],
        [10, 11],
        [14, 15]])]

In [130]:
np.hsplit(a,2)

[array([[ 0,  1],
        [ 4,  5],
        [ 8,  9],
        [12, 13]]),
 array([[ 2,  3],
        [ 6,  7],
        [10, 11],
        [14, 15]])]

In [131]:
np.vsplit(a,2)

[array([[0, 1, 2, 3],
        [4, 5, 6, 7]]),
 array([[ 8,  9, 10, 11],
        [12, 13, 14, 15]])]

# Useful numerical methods of Numpy array

In [133]:
m = np.arange(10,19).reshape(3,3)

In [134]:
m

array([[10, 11, 12],
       [13, 14, 15],
       [16, 17, 18]])

In [135]:
m.min()

10

In [136]:
m.max()

18

In [137]:
m.argmax()

8

In [138]:
m.argmin()

0

In [140]:
m.min(axis = 0)

array([10, 11, 12])

In [141]:
m.min(axis = 1)

array([10, 13, 16])

In [142]:
m.max(axis=1)

array([12, 15, 18])

In [144]:
m.sort(axis = 1)

In [145]:
# mean
m.mean()

14.0

In [146]:
# standard deviation
m.std()

2.581988897471611

In [147]:
# variance
m.var()

6.666666666666667

In [148]:
# sum all the values of the matrix
m.sum()

126

In [149]:
# multiply the entire matrix
m.prod()

463356416

In [150]:
m

array([[10, 11, 12],
       [13, 14, 15],
       [16, 17, 18]])

In [151]:
# commulative sum -> is the function which will add the next value in previous
m.cumsum()

array([ 10,  21,  33,  46,  60,  75,  91, 108, 126])

In [152]:
# cumulative product-> is the function which will product the next to the previous
m.cumprod()

array([       10,       110,      1320,     17160,    240240,   3603600,
        57657600, 980179200, 463356416])

In [153]:
# return true if all the elements of the matrix is true
m.all()

True

In [154]:
# return true if any the elements of the matrix is true
m.any()

True

In [155]:
[(m<15).any()]

[True]

In [156]:
(m<15).all()

False