# Numpy

Arrays 
1. faster
2. contigous memory allocation
3. same data types
4. if you want to increase size, recreate array

List
1. slow
2. parse memory
3. different data types
4. can dynamically grow

# A comarision of numpy vs list in python

In [1]:
import numpy as np

In [10]:
python_list = range(1000000) # A list from 0 to 1000000

In [11]:
numpy_array = np.arange(1000000) # An array form 0 to 1000000

In [12]:
# Multiply numpy array with 5
%time for i in range(1000): result = numpy_array * 5

CPU times: total: 2.08 s
Wall time: 2.13 s


In [13]:
# multiply a list with 5 
result = []
for i in python_list:
    result.append(i*5)

In [16]:
%time for i in range(10): result = [i*5 for i in python_list]

CPU times: total: 1.08 s
Wall time: 1.08 s


In [ ]:
#Numpy array creation method

In [18]:
one_d_array = np.zeros((10))
one_d_array

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [19]:
one_d_array = np.ones((10))
one_d_array

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [20]:
one_d_array*2

array([2., 2., 2., 2., 2., 2., 2., 2., 2., 2.])

In [28]:
#Creating array of any number
x = np.zeros(10)
x = x+5
x

array([5., 5., 5., 5., 5., 5., 5., 5., 5., 5.])

In [21]:
x = np.zeros(10) + 5
x

array([5., 5., 5., 5., 5., 5., 5., 5., 5., 5.])

In [23]:
x = np.arange(1, 11)
x

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [24]:
#shape of array
np.zeros((10, 5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [26]:
x = np.zeros((3, 2, 5))
x

array([[[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]]])

In [27]:
x.shape

(3, 2, 5)

In [29]:
#Array of custom elements

In [30]:
x = np.array([1,3,5,2,55,7,3,77])

In [31]:
x

array([ 1,  3,  5,  2, 55,  7,  3, 77])

In [32]:
x.shape

(8,)

In [35]:
y = x.reshape(2,4)

In [36]:
y.shape

(2, 4)

In [37]:
y.ndim

2

In [38]:
y

array([[ 1,  3,  5,  2],
       [55,  7,  3, 77]])

In [39]:
#Accessing individual elements of array

In [40]:
y[0,3]

2

In [41]:
y[1,0]

55

In [42]:
z = y.reshape(2,2,2)

In [43]:
z

array([[[ 1,  3],
        [ 5,  2]],

       [[55,  7],
        [ 3, 77]]])

In [45]:
z[0,1,1]

2

In [46]:
z.ndim

3

In [47]:
#Slicing

In [48]:
y

array([[ 1,  3,  5,  2],
       [55,  7,  3, 77]])

In [50]:
# Slicing: start, end, step
y = y.reshape(4,2)

In [51]:
y

array([[ 1,  3],
       [ 5,  2],
       [55,  7],
       [ 3, 77]])

In [52]:
y[0:3]

array([[ 1,  3],
       [ 5,  2],
       [55,  7]])

In [53]:
y

array([[ 1,  3],
       [ 5,  2],
       [55,  7],
       [ 3, 77]])

In [54]:
y[0:3,1]

array([3, 2, 7])

In [55]:
y

array([[ 1,  3],
       [ 5,  2],
       [55,  7],
       [ 3, 77]])

In [56]:
y[::2]

array([[ 1,  3],
       [55,  7]])

In [57]:
y[::,0]

array([ 1,  5, 55,  3])

In [58]:
x

array([ 1,  3,  5,  2, 55,  7,  3, 77])

In [60]:
x[[3,5]] #Fancy indexing

array([2, 7])

In [61]:
# Vectorized operation

In [62]:
x = np.array([1,5,7])
y = np.array([3,2,9])

In [63]:
x+y

array([ 4,  7, 16])

In [64]:
x/y

array([0.33333333, 2.5       , 0.77777778])

In [65]:
x*y

array([ 3, 10, 63])

In [66]:
x-y

array([-2,  3, -2])

In [67]:
1/x

array([1.        , 0.2       , 0.14285714])

In [68]:
x*y**2

array([  9,  20, 567])

In [69]:
# Shapes 

###### 00000
###### 11111
###### 11111
###### 11111
###### 00000

In [ ]:
arr = np.ones((5,5))

In [72]:
arr

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [73]:
arr[0] = 0
arr[4] = 0

In [74]:
arr

array([[0., 0., 0., 0., 0.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [0., 0., 0., 0., 0.]])

In [75]:
arr[0] = 0
arr[-1] = 0

###### 00000
###### 01110
###### 01110
###### 01110
###### 00000

In [77]:
 arr = np.zeros((5,5))

In [78]:
arr

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [79]:
arr[1:-1, 1:-1] = 1

In [80]:
arr

array([[0., 0., 0., 0., 0.],
       [0., 1., 1., 1., 0.],
       [0., 1., 1., 1., 0.],
       [0., 1., 1., 1., 0.],
       [0., 0., 0., 0., 0.]])

In [83]:
x = np.array([1,4,4,6,8,4,3])

In [84]:
x[-1]

3

In [85]:
x[-2]

4

In [86]:
x[-4]

6

# Assignment

 Checkerboard pattern

In [89]:
 a = np.zeros((10,10))

In [90]:
a

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [93]:
a[0:-1:2,0:-1:2] = 1

In [94]:
a

array([[1., 0., 1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1., 0., 0.],
       [1., 0., 1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1., 0., 0.],
       [1., 0., 1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1., 0., 0.],
       [1., 0., 1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1., 0., 0.],
       [1., 0., 1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [95]:
b = np.ones((10,10))

In [96]:
b

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [97]:
b[0:-1:2,0:-1:2] = 0

In [98]:
b

array([[0., 1., 0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [0., 1., 0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [0., 1., 0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [0., 1., 0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [0., 1., 0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

# Football ground
#### 00000
#### 11111
#### 00000
#### 11111
#### 00000
#### 11111

In [100]:
c = np.zeros((6,5))

In [101]:
c

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [104]:
c[1::2] = 1

In [105]:
c

array([[0., 0., 0., 0., 0.],
       [1., 1., 1., 1., 1.],
       [0., 0., 0., 0., 0.],
       [1., 1., 1., 1., 1.],
       [0., 0., 0., 0., 0.],
       [1., 1., 1., 1., 1.]])

In [107]:
np.empty((100,100))  # Random/ arbitrary values

array([[8.33883579e-312, 8.33883352e-312, 8.33885122e-312, ...,
        6.95187041e-310, 8.33841784e-312, 4.94065646e-324],
       [8.06358402e-313, 1.03977795e-312, 1.10343782e-312, ...,
        1.97626258e-323, 8.33885122e-312, 4.45619118e-313],
       [8.33844929e-312, 8.33885122e-312, 2.12199581e-313, ...,
        8.33885123e-312, 0.00000000e+000, 0.00000000e+000],
       ...,
       [4.03179214e-313, 1.35807732e-312, 8.91238232e-313, ...,
        0.00000000e+000, 8.33885160e-312, 0.00000000e+000],
       [8.33885160e-312, 8.33885160e-312, 8.33885160e-312, ...,
        1.06099791e-312, 8.31822350e-312, 8.33885160e-312],
       [8.33885161e-312, 0.00000000e+000, 0.00000000e+000, ...,
        8.33885161e-312, 3.60739298e-313, 1.50661703e-312]])

In [108]:
x

array([1, 4, 4, 6, 8, 4, 3])

In [109]:
x.dtype

dtype('int32')

In [110]:
#Comparion between metrices

In [111]:
salary = np.array([10,25, 5, 2])

In [112]:
salary [salary > 5]

array([10, 25])

In [113]:
#Numpy element-wise functions

In [114]:
nums = [10, 20, 45, 87,99]

In [115]:
np.sin(nums)

array([-0.54402111,  0.91294525,  0.85090352, -0.82181784, -0.99920683])

In [116]:
np.sqrt(nums)

array([3.16227766, 4.47213595, 6.70820393, 9.32737905, 9.94987437])

In [6]:
#Vectorization

In [7]:
arr = np.zeros((2,10))

In [9]:
arr+10 #10 is a scaler

array([[10., 10., 10., 10., 10., 10., 10., 10., 10., 10.],
       [10., 10., 10., 10., 10., 10., 10., 10., 10., 10.]])

In [10]:
arr2 = np.ones((2,10))

In [12]:
arr+arr2 #Both operands are arrays

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [13]:
# In python list

In [14]:
l1 = [1,2,4,5]
l2 = [3,4,6,7]

In [16]:
l1+l2 # not sum only concatinate

[1, 2, 4, 5, 3, 4, 6, 7]

In [17]:
# for adding two list start loop

In [18]:
sum = []

In [23]:
for i, _ in enumerate(l1):
    sum.append(l1[i] + l2[i])
print(sum)

[4, 6, 10, 12, 4, 6, 10, 12, 4, 6, 10, 12, 4, 6, 10, 12]


In [24]:
#where

In [25]:
marks = np.array([75,39,50,80,90])

In [29]:
x = np.where(marks>=50, "Pass", "Fail")

In [30]:
x

array(['Pass', 'Fail', 'Pass', 'Pass', 'Pass'], dtype='<U4')

In [31]:
salary = np.array([10,70,80,50,30])

In [33]:
incremented_salary = np.where(salary<50, salary*1.1, salary*1.05)

In [34]:
incremented_salary

array([11. , 73.5, 84. , 52.5, 33. ])

In [36]:
arr = np.arange(1,101).reshape((10,10))

In [37]:
arr

array([[  1,   2,   3,   4,   5,   6,   7,   8,   9,  10],
       [ 11,  12,  13,  14,  15,  16,  17,  18,  19,  20],
       [ 21,  22,  23,  24,  25,  26,  27,  28,  29,  30],
       [ 31,  32,  33,  34,  35,  36,  37,  38,  39,  40],
       [ 41,  42,  43,  44,  45,  46,  47,  48,  49,  50],
       [ 51,  52,  53,  54,  55,  56,  57,  58,  59,  60],
       [ 61,  62,  63,  64,  65,  66,  67,  68,  69,  70],
       [ 71,  72,  73,  74,  75,  76,  77,  78,  79,  80],
       [ 81,  82,  83,  84,  85,  86,  87,  88,  89,  90],
       [ 91,  92,  93,  94,  95,  96,  97,  98,  99, 100]])

In [38]:
arr.T

array([[  1,  11,  21,  31,  41,  51,  61,  71,  81,  91],
       [  2,  12,  22,  32,  42,  52,  62,  72,  82,  92],
       [  3,  13,  23,  33,  43,  53,  63,  73,  83,  93],
       [  4,  14,  24,  34,  44,  54,  64,  74,  84,  94],
       [  5,  15,  25,  35,  45,  55,  65,  75,  85,  95],
       [  6,  16,  26,  36,  46,  56,  66,  76,  86,  96],
       [  7,  17,  27,  37,  47,  57,  67,  77,  87,  97],
       [  8,  18,  28,  38,  48,  58,  68,  78,  88,  98],
       [  9,  19,  29,  39,  49,  59,  69,  79,  89,  99],
       [ 10,  20,  30,  40,  50,  60,  70,  80,  90, 100]])

In [39]:
arr

array([[  1,   2,   3,   4,   5,   6,   7,   8,   9,  10],
       [ 11,  12,  13,  14,  15,  16,  17,  18,  19,  20],
       [ 21,  22,  23,  24,  25,  26,  27,  28,  29,  30],
       [ 31,  32,  33,  34,  35,  36,  37,  38,  39,  40],
       [ 41,  42,  43,  44,  45,  46,  47,  48,  49,  50],
       [ 51,  52,  53,  54,  55,  56,  57,  58,  59,  60],
       [ 61,  62,  63,  64,  65,  66,  67,  68,  69,  70],
       [ 71,  72,  73,  74,  75,  76,  77,  78,  79,  80],
       [ 81,  82,  83,  84,  85,  86,  87,  88,  89,  90],
       [ 91,  92,  93,  94,  95,  96,  97,  98,  99, 100]])

In [40]:
arr.transpose()

array([[  1,  11,  21,  31,  41,  51,  61,  71,  81,  91],
       [  2,  12,  22,  32,  42,  52,  62,  72,  82,  92],
       [  3,  13,  23,  33,  43,  53,  63,  73,  83,  93],
       [  4,  14,  24,  34,  44,  54,  64,  74,  84,  94],
       [  5,  15,  25,  35,  45,  55,  65,  75,  85,  95],
       [  6,  16,  26,  36,  46,  56,  66,  76,  86,  96],
       [  7,  17,  27,  37,  47,  57,  67,  77,  87,  97],
       [  8,  18,  28,  38,  48,  58,  68,  78,  88,  98],
       [  9,  19,  29,  39,  49,  59,  69,  79,  89,  99],
       [ 10,  20,  30,  40,  50,  60,  70,  80,  90, 100]])

In [41]:
arr = np.array([1, 3, 4, 5, 2])

In [42]:
arr.mean()

3.0

In [43]:
arr.cumsum()

array([ 1,  4,  8, 13, 15])

In [45]:
arr.cumprod()

array([  1,   3,  12,  60, 120])

In [46]:
# Procedure vs. Function
#Procedure doesn't return any value
#Function returns a value

In [47]:
#Methods for boolean arrays

In [48]:
gender = np.array(["Male", "Female", "Male", "Male", "Male"])

In [49]:
gender[gender=='Male']

array(['Male', 'Male', 'Male', 'Male'], dtype='<U6')

In [50]:
arr = gender=="Male"

In [51]:
arr

array([ True, False,  True,  True,  True])

In [52]:
arr.sum()

4

In [54]:
arr = gender == "Female"

In [55]:
arr.sum()

1

In [56]:
arr.any()

True

In [57]:
arr.all()

False

In [58]:
arr = np.array([2, 4, 10, 20, 16])

In [59]:
x = arr%2 == 0

In [60]:
x

array([ True,  True,  True,  True,  True])

In [61]:
x.all()

True

In [63]:
# Universal Quantifier
# Existential Quantifier

In [64]:
arr

array([ 2,  4, 10, 20, 16])

In [66]:
arr.sort() #Inplace

In [67]:
arr[::-1]

array([20, 16, 10,  4,  2])

In [68]:
arr = np.array([1,2,4,1,6,2])

In [70]:
u = np.unique(arr)

In [72]:
# Save Array

In [73]:
np.save('data', u)

In [74]:
 # load array

In [75]:
content = np.load('data.npy')

In [76]:
content

array([1, 2, 4, 6])

In [77]:
# Saving multiple arrays

In [78]:
students = np.array(["Ali", "Asad", "Ahmed"])
marks = np.array([30, 20, 60])

In [79]:
np.savez('arrays', std=students, m=marks)

In [83]:
result = np.load('arrays.npz')

In [84]:
result['std']

array(['Ali', 'Asad', 'Ahmed'], dtype='<U5')

In [85]:
result['m']

array([30, 20, 60])

In [86]:
#Linear Algebra Function

In [87]:
arr = np.arange(16).reshape(4,4)

In [88]:
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [95]:
arr.diagonal() # diagonal of a matrix

array([ 0,  5, 10, 15])

In [96]:
arr.trace()

30

In [98]:
arr1=np.arange(10,26).reshape(4,4)

In [100]:
arr1

array([[10, 11, 12, 13],
       [14, 15, 16, 17],
       [18, 19, 20, 21],
       [22, 23, 24, 25]])

In [99]:
arr.dot(arr1)

array([[ 756,  802,  848,  894],
       [1012, 1074, 1136, 1198],
       [1268, 1346, 1424, 1502],
       [1524, 1618, 1712, 1806]])

In [103]:
from numpy import linalg

In [104]:
linalg.det(arr)

0.0

In [105]:
linalg.eig(arr)

(array([ 7.11247837e+01, -1.12478374e+00, -2.94014727e-15,  7.59746340e-16]),
 array([[-0.32127676,  0.70087495,  0.49149433, -0.05161591],
        [-0.43035796,  0.25454278, -0.47515096, -0.33761028],
        [-0.53943916, -0.19178939, -0.52418105,  0.83006828],
        [-0.64852036, -0.63812155,  0.50783769, -0.44084209]]))

In [107]:
linalg.inv([[1, 5], [9, 8]])

array([[-0.21621622,  0.13513514],
       [ 0.24324324, -0.02702703]])

In [108]:
linalg.qr(arr)

(array([[-0.30096463, -0.78065376, -0.28906053, -0.46523544],
        [-0.42135049, -0.34994824,  0.73218006,  0.40486092],
        [-0.54173634,  0.08075729, -0.59717853,  0.58598447],
        [-0.66212219,  0.51146281,  0.154059  , -0.52560995]]),
 array([[-3.32264955e+01, -3.51526691e+01, -3.70788428e+01,
         -3.90050164e+01],
        [ 0.00000000e+00, -5.38381902e-01, -1.07676380e+00,
         -1.61514571e+00],
        [ 0.00000000e+00,  0.00000000e+00, -5.18368350e-15,
         -5.45951253e-15],
        [ 0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
          8.06562129e-15]]))

In [109]:
linalg.svd(arr)

(array([[-0.31904962, -0.77343865,  0.52129704, -0.16807556],
        [-0.42937998, -0.34004828, -0.5697866 ,  0.61265262],
        [-0.53971034,  0.09334209, -0.42431793, -0.72107856],
        [-0.6500407 ,  0.52673246,  0.47280749,  0.2765015 ]]),
 array([7.23794055e+01, 1.10528678e+00, 4.63535513e-15, 2.02077729e-15]),
 array([[-0.45893576, -0.48571383, -0.5124919 , -0.53926997],
        [ 0.69955555,  0.25314438, -0.1932668 , -0.63967797],
        [-0.33003629,  0.11423655,  0.76163579, -0.54583604],
        [-0.43712246,  0.82882448, -0.34628157, -0.04542044]]))

In [110]:
np.random.normal(3,4,(3,3))

array([[-3.7225333 ,  5.91448832,  0.48690477],
       [ 4.92654752,  0.45213868,  2.17289934],
       [-4.66589144,  2.57732167, -2.86852332]])

In [113]:
np.random.gamma(1,2,(4,4))

array([[ 0.14756486,  1.5418061 ,  0.80382049,  3.14650724],
       [ 6.53345832,  1.14017099,  7.00183906,  0.83541646],
       [ 5.69690498,  3.81098061,  0.80816399,  4.87078557],
       [ 1.23851279,  0.24171154, 10.30826283,  5.99309969]])

In [114]:
np.random.seed(5)

In [116]:
np.random.rand()

0.22199317108973948

In [117]:
# Reshape

In [118]:
arr

array([[10, 11, 12, 13],
       [14, 15, 16, 17],
       [18, 19, 20, 21],
       [22, 23, 24, 25]])

In [119]:
arr.reshape((2,2,2,2))

array([[[[10, 11],
         [12, 13]],

        [[14, 15],
         [16, 17]]],


       [[[18, 19],
         [20, 21]],

        [[22, 23],
         [24, 25]]]])

In [120]:
arr = np.arange(16)

In [122]:
arr.reshape((4,4),order='F') # Column major order

array([[ 0,  4,  8, 12],
       [ 1,  5,  9, 13],
       [ 2,  6, 10, 14],
       [ 3,  7, 11, 15]])

In [126]:
arr.reshape((4,4),order='c') # Row major order

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [127]:
 # Converting to 1D array

In [128]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [129]:
arr = np.array([[1, 8, 7],[3, 4, 5],[9, 0, 1]])

In [130]:
arr

array([[1, 8, 7],
       [3, 4, 5],
       [9, 0, 1]])

In [131]:
arr.flatten()

array([1, 8, 7, 3, 4, 5, 9, 0, 1])

In [133]:
 arr.ravel()

array([1, 8, 7, 3, 4, 5, 9, 0, 1])

In [134]:
arr.reshape(1,9)

array([[1, 8, 7, 3, 4, 5, 9, 0, 1]])

In [135]:
# Assignment: Difference between ravel and flatten

In [136]:
 # Concatenate

In [137]:
a = np.array([[1, 2],[3, 4]])
b = np.array([[7, 8], [9, 10]])

In [140]:
print('a=',a)
print('b=',b)

a= [[1 2]
 [3 4]]
b= [[ 7  8]
 [ 9 10]]


In [138]:
np.concatenate((a,b),axis=0)

array([[ 1,  2],
       [ 3,  4],
       [ 7,  8],
       [ 9, 10]])

In [142]:
a = np.array([[1, 7, 9],[2, 3, 4,],[5, 6, 7]])
b = np.array([[9, 4, 9],[2, 3, 2],[0, 6, 7]])

In [143]:
np.concatenate((a, b))

array([[1, 7, 9],
       [2, 3, 4],
       [5, 6, 7],
       [9, 4, 9],
       [2, 3, 2],
       [0, 6, 7]])

In [145]:
np.hstack((a, b))  # concatenate axis = 1

array([[1, 7, 9, 9, 4, 9],
       [2, 3, 4, 2, 3, 2],
       [5, 6, 7, 0, 6, 7]])

In [147]:
np.vstack((a, b))  # concatenate axis = 0

array([[1, 7, 9],
       [2, 3, 4],
       [5, 6, 7],
       [9, 4, 9],
       [2, 3, 2],
       [0, 6, 7]])

In [148]:
np.r_[a,b]  # concatenate axis = 0

array([[1, 7, 9],
       [2, 3, 4],
       [5, 6, 7],
       [9, 4, 9],
       [2, 3, 2],
       [0, 6, 7]])

In [149]:
np.c_[a,b]  # concatenate axis = 1

array([[1, 7, 9, 9, 4, 9],
       [2, 3, 4, 2, 3, 2],
       [5, 6, 7, 0, 6, 7]])

In [150]:
# Split Function

In [151]:
x = np.array([1, 9, 9, 7, 1, 2, 3])

In [153]:
np.split(x,[3, 5])

[array([1, 9, 9]), array([7, 1]), array([2, 3])]

In [161]:
l = np.arange(2, 7, 2)

In [162]:
l

array([2, 4, 6])

In [164]:
x

array([1, 9, 9, 7, 1, 2, 3])

In [165]:
np.split(x,l)

[array([1, 9]), array([9, 7]), array([1, 2]), array([3])]

In [170]:
x = np.array([[1, 3], [2, 4]])

In [171]:
x

array([[1, 3],
       [2, 4]])

In [172]:
np.split(x,[1])

[array([[1, 3]]), array([[2, 4]])]