In [2]:
from sklearn.datasets import load_iris
iris = load_iris()
X = iris.data
y = iris.target
feature_names = iris.feature_names
target_names = iris.target_names
print('Features names:', feature_names)
print('Target names:', target_names)

Features names: ['sepal length (cm)', 'sepal width (cm)', 'petal length (cm)', 'petal width (cm)']
Target names: ['setosa' 'versicolor' 'virginica']


In [3]:
print(X.shape)

(150, 4)


In [4]:
print('\nFirst 10 rows of X:\n',X[:10])


First 10 rows of X:
 [[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]
 [5.4 3.9 1.7 0.4]
 [4.6 3.4 1.4 0.3]
 [5.  3.4 1.5 0.2]
 [4.4 2.9 1.4 0.2]
 [4.9 3.1 1.5 0.1]]


In [5]:
print('\n',y[:10])


 [0 0 0 0 0 0 0 0 0 0]


In [7]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.3, random_state = 1, shuffle=True)

In [9]:
from sklearn.neighbors import KNeighborsClassifier
from sklearn import metrics 

In [10]:
classifier_knn = KNeighborsClassifier(n_neighbors=3)
classifier_knn.fit(X_train, y_train)

KNeighborsClassifier(n_neighbors=3)

In [12]:
y_pred = classifier_knn.predict(X_test)

In [13]:
print('Accuracy:', metrics.accuracy_score(y_test, y_pred))

Accuracy: 0.9777777777777777


In [15]:
sample = [[5, 5, 3, 2], [2, 4, 3, 5]]
preds = classifier_knn.predict(sample)
print(preds)

[1 2]


In [17]:
print(iris.target_names)

['setosa' 'versicolor' 'virginica']


In [18]:
pred_species = [iris.target_names[p] for p in preds]
print("Predictions: ", pred_species)

Predictions:  ['versicolor', 'virginica']


In [19]:
#Shap: Explainable AI

In [20]:
#Assignment: Train a model using these algorithms:
#Decision Tree
#k-NN
#Random forest
#Support vector machines
#NaiveBayes
#Check accuracy, precision, recall

In [21]:
#Saving and loading the model

In [26]:
from sklearn.externals import joblib
joblib.dump(classifier_knn, 'iris_classifier_knn.joblib')

ImportError: cannot import name 'joblib' from 'sklearn.externals' (C:\Users\Nasrullah Khan\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\externals\__init__.py)

In [28]:
from sklearn.externals import joblib
joblib.dump(classifier_knn, 'iris_classifier_knn.joblib')

ImportError: cannot import name 'joblib' from 'sklearn.externals' (C:\Users\Nasrullah Khan\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\externals\__init__.py)

In [1]:
model = joblib.load(iris_clas)

NameError: name 'joblib' is not defined

In [2]:
import pandas as pd

In [3]:
frame = pd.DataFrame({
    'age': [12, 13, 14],
    'salary': [34, 37, 39],
    'life expectancy': [60, 76, 23]
})

In [4]:
frame.corr()

age    salary  life expectancy
age              1.000000  0.993399        -0.680534
salary           0.993399  1.000000        -0.591993
life expectancy -0.680534 -0.591993         1.000000

In [5]:
# Preprocessing using machine learning

In [6]:
import numpy as np
from sklearn import preprocessing 
input_data = np.array(
    [
        [2.1, -1.9, 5.5],
        [-1.5, 2.4, 3.5],
        [0.5, -7.9, 5.6],
        [5.9, 2.3, -5.8]
    ]
)

In [7]:
#Scaling/ normalization

In [8]:
data_scaling_minmax = preprocessing.MinMaxScaler(feature_range=(0,1))
data_scaled_minmax = data_scaling_minmax.fit_transform(input_data)
print("\nMin Max scaled data:\n", data_scaled_minmax)


Min Max scaled data:
 [[0.48648649 0.58252427 0.99122807]
 [0.         1.         0.81578947]
 [0.27027027 0.         1.        ]
 [1.         0.99029126 0.        ]]


In [9]:
#SVM